name: 🐛 Bug Report
description: Create a report to help us improve the platform
title: "fix: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to report an issue!
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '/fr/contact'
        2. Fill out the form
        3. See error
    validations:
      required: true
  - type: input
    id: browser
    attributes:
      label: Browser & OS
      description: What browser and operating system were you using?
      placeholder: Chrome 128 / macOS 14.5
    validations:
      required: false
