name: 🚀 Feature Request
description: Suggest an idea or capability for Digital Station
title: "feat: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: Share your feature proposal or enhancement idea!
  - type: textarea
    id: problem
    attributes:
      label: Problem or Use Case
      description: Is your feature request related to a problem or business use case?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
